name: dart_frog_first
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.8
  json_annotation: ^4.10.0

dev_dependencies:
  build_runner: ^2.10.5
  dart_frog_lint: ^0.1.0
  json_serializable: ^6.12.0
  mocktail: ^1.0.3
  test: ^1.25.5
